version: '3'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak-db:
      image: postgres:latest
      container_name: keycloak-db
      restart: unless-stopped
      networks:
        - kommonitor
      volumes:
        - ./database/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak-data
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      networks:
        - kommonitor
      ports:
        - 8080:8080
      volumes:
        - ../realms/realm-export-kommonitor.json:/opt/keycloak/data/import/realm.json
      command:
        - start-dev
        - --import-realm
      restart: unless-stopped
      depends_on:
        - keycloak-db
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL_HOST=keycloak-db
        - KC_DB_URL_DATABASE=keycloak-data
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=keycloak
        - KC_DB_SCHEMA=public
