version: '3.8'
name: kommonitor-dev

networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  kommonitor-client:
    image: 'kommonitor/web-client:3.2.0-beta.5'
    container_name: kommonitor-client
    restart: unless-stopped
    volumes:
      - ../../config/templates/config-storage-server.json.template:/code/templates/config-storage-server.json.template
      - ../../config/config.sh:/code/config.sh
      - ./storage/client/config-storage-server.json:/usr/share/nginx/html/config/config-storage-server.json
    environment:
      - KOMMONITOR_NAME=kommonitor-web-client
    env_file:
      - ../../config/client.env
    ports:
      - 8084:80
    networks:
      - kommonitor
    command: ["/bin/sh", "/code/config.sh"]

  kommonitor-client-config:
    image: 'kommonitor/client-config:2.1.0'
    container_name: kommonitor-client-config
    restart: unless-stopped
    ports:
      - 8088:8088
    networks:
      - kommonitor
    volumes:
      - ../../config/templates:/code/templates
      - ../../config/config.sh:/code/config.sh
      - ./storage/config_server:/code/configStorage
    environment:
      - KOMMONITOR_NAME=kommonitor-client-config
    env_file:
      - ../../config/client-config.env
    command: ["/bin/sh", "/code/config.sh"]

  redis:
    image: redis:alpine
    container_name: kommonitor-redis
    restart: unless-stopped
    networks:
      - kommonitor

  kommonitor-processing-engine:
    image: 'kommonitor/processing-engine:2.0.2'
    container_name: kommonitor-processing-engine
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - kommonitor
    volumes:
      - ./storage/processing_engine:/code/tmp
    depends_on:
      - redis
    env_file:
      - ../../config/processing-engine.env

  kommonitor-processing-scheduler:
    image: 'kommonitor/processing-scheduler:2.0.2'
    container_name: kommonitor-processing-scheduler
    restart: unless-stopped
    networks:
      - kommonitor
    depends_on:
      - kommonitor-processing-engine
      - kommonitor-data-management
    env_file:
      - ../../config/processing-scheduler.env

  kommonitor-importer:
    image: 'kommonitor/importer:3.2.4'
    container_name: kommonitor-importer
    restart: unless-stopped
    networks:
      - kommonitor
    ports:
      - 8087:8087
    volumes:
      - ./storage/importer:/tmp/kommonitor
    env_file:
      - ../../config/importer.env
      - ../../config/keycloak.env

  kommonitor-db:
    image: postgis/postgis:15-master
    container_name: kommonitor-db
    restart: unless-stopped
    networks:
      - kommonitor
    ports:
      - 5432:5432
    volumes:
      - ./storage/database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ../../config/db.env

  kommonitor-data-management:
    image: kommonitor/data-management:4.1.0-beta.2
    container_name: kommonitor-data-management
    restart: unless-stopped
    depends_on:
      kommonitor-db:
        condition: service_healthy
    ports:
      - "8085:8085"
    networks:
      - kommonitor
    links:
      - kommonitor-db
    env_file:
      - ../../config/data-management.env
      - ../../config/keycloak.env

  kommonitor-spatial-data-processor:
    image: kommonitor/spatial-data-processor:1.0.4
    container_name: kommonitor-spatial-data-processor
    restart: unless-stopped
    networks:
      - kommonitor
    ports:
      - 8090:8090
    volumes:
      - ../../data/basis-dlm:/opt/kommonitor/data/basis-dlm
    env_file:
      - ../../config/spatial-data-processor.env

  # optional pgadmin container to inspect the database
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - 8083:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@kommonitor.de
  #     - PGADMIN_DEFAULT_PASSWORD=kommonitor
    # volumes:
    #   - /var/kommonitor/pgadmin/servers.json:/pgadmin4/servers.json
    #   - /var/kommonitor/pgadmin/pgadmin:/var/lib/pgadmin
    # networks:
    #   - kommonitor