version: '3'

networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: kommonitor-traefik-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/config"
    ports:
      - 443:443
      - 9080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik/config
      - ../certs/cert.pem:/etc/certs/kommonitor-cert.pem
      - ../certs/key.pem:/etc/certs/kommonitor-key.pem
    networks:
      - kommonitor