version: '3'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    # container_name: keycloak
    volumes:
      - ./themes/kommonitor:/opt/keycloak/themes/kommonitor
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    command:
      - start-dev
      - --import-realm
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - kommonitor