version: '3'

# volumes:
#   postgres_data_keycloak:
#       driver: local
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak-db:
      image: postgres:latest
      container_name: keycloak-db
      restart: unless-stopped
      networks:
        - kommonitor
      volumes:
        # - postgres_data_keycloak:/var/lib/postgresql/data
        - ./database/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak-data
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: kbkajhsbf23hgv
  keycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      networks:
        - kommonitor
      ports:
        - 8080:8080
      volumes:
        - ./themes/kommonitor:/opt/jboss/keycloak/themes/kommonitor
        - ./realms/realm-export_template_localhost.json:/tmp/realm-export.json
      restart: unless-stopped
      environment:
        - DB_VENDOR=postgres
        - DB_ADDR=keycloak-db
        - DB_DATABASE=keycloak-data
        - DB_USER=keycloak
        - DB_SCHEMA=public
        - DB_PASSWORD=kbkajhsbf23hgv        
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=KiTdNnJikOBRIEMnAI4U
        - KEYCLOAK_IMPORT=/tmp/realm-export.json
        - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
        - PROXY_ADDRESS_FORWARDING=true
      depends_on:
        - keycloak-db
