version: '3'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    networks:
      - kommonitor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d keycloak-data -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak-data
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./realms/realm-export-kommonitor.json:/opt/keycloak/data/import/realm.json
      - ../certs:/opt/keycloak/demo/certs
    command:
      - start
      - --import-realm
    expose:
      - 8080
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - kommonitor
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak-data
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_SCHEMA=public
      - KC_HOSTNAME=keycloak
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/demo/certs/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/demo/certs/key.pem
      - KC_SPI_CONNECTIONS_JPA_LEGACY_MIGRATION_STRATEGY=update