version: '3.1'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./realms/realm-export-kommonitor-token-exchange.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
      - --features=token-exchange,admin-fine-grained-authz
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - kommonitor
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file