version: '3.1'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak:
    image: kommonitor/keycloak:26.3.4-postgres
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./realms/realm-export-kommonitor.json:/opt/keycloak/data/import/realm.json
    command:
      - --import-realm
      - --features=admin-fine-grained-authz:v1,scripts,token-exchange:v1
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - kommonitor
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=dev-file