version: '3'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak:
      image: jboss/keycloak:latest
      # container_name: keycloak
      networks:
        - kommonitor
      ports:
        - 8080:8080
      volumes:
        - ../realms/realm-export-kommonitor.json:/tmp/realm-export.json
      restart: unless-stopped
      environment:
        - DB_VENDOR=h2      
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - KEYCLOAK_IMPORT=/tmp/realm-export.json
        - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
        - PROXY_ADDRESS_FORWARDING=true
